### ISSUE TITLE
Won't compile on avr-gcc 4.7.2

### ISSUE THREAD

**Issue by sycophantic** [wbphelps/Ice-Tube-Clock#1]
Based on this post: http://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&p=871000

It looks like memory / flash allocation has changed: http://forums.adafruit.com/viewtopic.php?f=47&t=35660#p183795

```
-------- begin --------
avr-gcc (GCC) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Compiling: iv.c
avr-gcc -c -mmcu=atmega328p -I. -g -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -Wall -Wstrict-prototypes -DF_CPU=8000000 -Wa,-adhlns=iv.lst  -std=gnu99 -DTXMODE=   iv.c -o iv.o
In file included from iv.c:76:0:
util.h:62:0: warning: "nop" redefined [enabled by default]
In file included from iv.c:75:0:
iv.h:409:0: note: this is the location of the previous definition
In file included from iv.c:77:0:
fonttable.h:41:7: error: variable ‘alphatable_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
fonttable.h:41:30: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
fonttable.h:62:7: error: variable ‘numbertable_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
fonttable.h:62:31: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
iv.c:124:7: error: variable ‘dialsegs1_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:124:29: warning: initialization from incompatible pointer type [enabled by default]
iv.c:129:7: error: variable ‘dialsegs2_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:129:29: warning: initialization from incompatible pointer type [enabled by default]
iv.c:134:7: error: variable ‘dialsegs3_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:134:29: warning: initialization from incompatible pointer type [enabled by default]
iv.c:137:7: error: variable ‘dialsegs4_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:137:29: warning: initialization from incompatible pointer type [enabled by default]
iv.c:205:7: error: variable ‘digittable_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:205:30: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
iv.c:213:7: error: variable ‘segmenttable_p’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
iv.c:213:32: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
make: *** [iv.o] Error 1
```

**Comment by wbphelps** [comment]
The latest branch v130621wm compiles without error on avr 4.7.2.

**Comment by sycophantic** [comment]
Thanks.  I didn't realize master wasn't the latest.

**Comment by wbphelps** [comment]
I guess I should merge all the updates into master now. I was waiting until it had been tested by at least one other person.
